apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: flehskjcr-java-springboot
  janus-idp.io/tekton: flehskjcr-java-springboot
  backstage.io/kubernetes-id: flehskjcr-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: flehskjcr-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
